### PR TITLE
fix: allow signing RPMs for DNF

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by ctron** [comment]
@tobias1703 this is a draft PR, which requires SNAPSHOT version of packager too (https://github.com/eclipse/packager/pull/44), but solves the issue for me.

**Comment by ctron** [comment]
@tisoft I would like to have your thoughts in this PR. As the new version adds additional headers, the checksum of the file will change. This is why the two "reproducible" tests fail. The checksum itself seems stable though.

So, this might be a bit on the expectation of a reproducible build: one could argue that the tool is part of this, and upgrading the tool, might result in a different outcome. Which is what happens here.

An alternative could be to suppress the new information by configuration, which might then sum up configuration option over time, but could allow for the same outcome, independent of the tool version.

I would opt of the first option (not only because I am a bit lazy :grimacing:), but also because any future change could simply make it impossible provide this kind of guarantee.

Besides, you can also re-produce the old RPM, bit-by-bit, when using the old version of the RPM builder.

**Comment by tisoft** [comment]
The tooling is very much part of a build being reproducible. So just update the checksum in the tests.

**Comment by ctron** [comment]
Thanks for the quick response!

**Pull request merged**
