### PR TITLE
Fixed repodata creation for multiple rpms

### LINKED ISSUE #12: yum-repository goal creates wrong repodata for multiple RPMs
When creating a yum repository using the yum-repository goal with **more than one** RPM, the RPMs are successfully copied into the `packages` folder, but the metadata folder contains only metadata for **one** package. This is easily reproducible by running the plugin with more than one RPM to add and afterwards checking the `*-filelists.xml` file in the repodata directory.

### PR DESCRIPTION
**Pull request by triggetry**
The creation of repodata files was broken when more than one rpm were added to the yum repository. More specifically, the resulting metadata `*.xml` files have been overwritten in each loop iteration, resulting in having only one package defined in the repodata files. Thus, the `yum-repository` goal was not usable when intending to add more than one rpm to the repository.

This PR fixes #12  by making sure that the `context` variable to add rpm packages gets reused in each loop iteration instead of recreated.

### CODE REVIEW

**Comment by ctron** [comment]
Big thanks! Let me know when I should make a new release of the plugin.

**Comment by triggetry** [comment]
Thanks for responding so fast :) It would be really cool to release a new version right away.

**Comment by ctron** [comment]
The release is done. It may take a while into it is synced with Maven central.

Many thanks for the PR!

**Comment by ctron** [comment]
@triggetry Do you have a Twitter handle for mentioning you?

**Comment by triggetry** [comment]
@ctron sure, https://twitter.com/triggetry

**Comment by ctron** [comment]
That was easy 😁

**Pull request merged**
