### PR TITLE
Feature/snapshot version

### PR DESCRIPTION
**Pull request by elkman**
Hi @ctron,

it took me a while to get around to it, but here is my PR for #52.

I hope it's ok and fits with the rest of the code.

### CODE REVIEW

**Comment by ctron** [comment]
Thanks for the PR! No worries, this looks great.

Just to be sure, this is a non-breaking change, right? The existing behavior should be the same, only when you opt in to the new flag, you would see the change?

**Comment by elkman** [comment]
Yes, non-breaking was my intention. Since the additional code only takes effect if the snapshotVersion parameter is non-empty, this should be safe. Only the log output for SNAPSHOT builds has changed, but hopefully nobody will mind that.

**Review by ctron — APPROVED** [review]

**Comment by ctron** [comment]
I just released this in 1.6.0 of the plugin … it would be great if you could give it a try and let me know if it works as expected. Thanks a lot for the contribution!

**Comment by elkman** [comment]
> I just released this in 1.6.0 of the plugin … it would be great if you could give it a try and let me know if it works as expected.

I pulled the version from the public maven repo and everything works as expected.

Thanks for the support and the quick release.

BTW: On GitHub v1.4.0 is still tagged as _latest_.

**Comment by ctron** [comment]
Thanks for the contribution! Indeed, I added the 1.6.0 release information … and I am also in process of uploading the documentation.

**Pull request merged**
