### PR TITLE
Reproducible RPMs

### LINKED ISSUE #60: RPM builds are not reproducible
RPMs build by the rpm-builder are not reproducible.

Following issues have been found:

- Dependency sorting is not stable, if two dependencies are equal in name and version, but differ in their flags, they are sorted differently each time, leading to a different RPM (Caused by https://github.com/eclipse/packager/issues/18, fixed by https://github.com/eclipse/packager/pull/19)
- Inode numbers are not reproducible
- timestamps can't be set

### PR DESCRIPTION
**Pull request by tisoft**
Fixes #60

### CODE REVIEW

**Comment by tisoft** [comment]
This needs https://github.com/eclipse/packager/pull/19. Until that is released, I have used a jitpack build to get the updated dependency. Will replace that commit with the correct released version as soon as possible.

I have added a dependency on `maven-archiver`. It is only used to parse the `outputTimestamp`. It allows us to have the same parsing, as the maven-jar-plugin and other official plugins use for reproducible builds. If you don't want that dependency, I can implement the parsing myself, but it could diverge from the 'official' solution then.

The parameter can be controlled with the `${project.build.outputTimestamp}` property. That is the same property the official maven plugins use.

Of course, the RPM is only reproducible, if everything that is packaged into the RPM is reproducible as well, so using the same property as the other plugins makes sense to me.

**Comment by tisoft** [comment]
Marked as draft as long as the jitpack repo is used

**Comment by tisoft** [comment]
tests fail in CI, but run locally. Unfortunately the output of the verify.groovy scripts was not in the logs. The update to invoker 3.2.2 should fix the log output, so that I can see the test failures. There is probably still something machine depending in the rpm.

**Comment by tisoft** [comment]
@ctron Ready for review, from my point of view. 😁

**Review by ctron — APPROVED** [review]

**Comment by ctron** [comment]
LGTM! Want me to merge and release?

**Comment by tisoft** [comment]
Merge and Release would be great. .)

**Comment by ctron** [comment]
And it's released: https://repo.maven.apache.org/maven2/de/dentrassi/maven/rpm/1.8.0/

**Pull request merged**
