### PR TITLE
Bugfix rpm dependencies in YumMojo

### PR DESCRIPTION
**Pull request by triggetry**
The yum-repository goal fails, when there are maven dependencies with type other than "rpm".
In this PR i propose to filter out only those dependencies with type "rpm".

### CODE REVIEW

**Comment by ctron** [comment]
Big thanks for the fixes! I will try to make a release in the next few days!

**Comment by ctron** [comment]
I uploaded a release candidate to the OSSRH repository in staging. It would be great if you could give it a try!

**Comment by triggetry** [comment]
thank you, I've tried to use the release candidate - seems to work fine :)

**Comment by ctron** [comment]
Cool! I will release it then.

**Comment by triggetry** [comment]
Awesome, thanx :)

**Pull request merged**
